name: Build and Deploy to Appetize

on:
  push:
    branches: [main]

jobs:
  build-ios:
    runs-on: macos-latest

    steps:
    - name: Checkout repo
      uses: actions/checkout@v3

    - name: Set up Xcode
      run: sudo xcode-select -s /Applications/Xcode_15.0.app || true

    - name: Build app for simulator
      run: |
        xcodebuild -scheme KiwiCompanionApp \
                   -destination 'generic/platform=iOS Simulator' \
                   -configuration Debug \
                   -derivedDataPath build

    - name: Package .app into Payload.zip
      run: |
        mkdir -p Payload
        cp -r build/Build/Products/Debug-iphonesimulator/*.app Payload/
        zip -r Payload.zip Payload

    - name: Upload to Appetize.io
      env:
        APPETIZE_API_TOKEN: ${{ secrets.APPETIZE_API_TOKEN }}
      run: |
        curl https://uploader.appetize.io/v1/apps \
          -F "file=@Payload.zip" \
          -F "platform=ios" \
          -F "token=$APPETIZE_API_TOKEN"